Chance: 0.5 #此选项代表每次玩家执行完效果 即生成牛奶桶后有多少概率会让玩家怀孕 默认0.5 也就是50%
# 如果以下两项都为false 则表示玩家不会怀孕
Gril:
  enabled: true #是否开启怀孕为女孩的结果 默认true
  chance: 0.5 #代表怀女孩的概率 默认0.5 也就是50%
Boy:
  enabled: true #是否开启怀孕为男孩的结果 默认true
  chance: 0.5 #代表怀男孩的概率 默认0.5 也就是50%
